version: '2'

services:  
  filebeat:
    build: ./
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock
    environment:
     - LOGSTASH_HOST=172.18.0.4
     - LOGSTASH_PORT=5000
     - SHIPPER_NAME=someMaciejShipperName
    networks:
      - dockerelk_docker_elk
networks:
  dockerelk_docker_elk:
    external: true
